// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from './routes/_404.tsx';
import * as $_app from './routes/_app.tsx';
import * as $future_layout from './routes/future/_layout.tsx';
import * as $future_index from './routes/future/index.tsx';
import * as $game_layout from './routes/game/_layout.tsx';
import * as $game_index from './routes/game/index.tsx';
import * as $index from './routes/index.tsx';
import * as $monitor_layout from './routes/monitor/_layout.tsx';
import * as $monitor_index from './routes/monitor/index.tsx';
import * as $nas_layout from './routes/nas/_layout.tsx';
import * as $nas_index from './routes/nas/index.tsx';
import * as $nas_upload from './routes/nas/upload.tsx';
import * as $AnimationProvider from './islands/AnimationProvider.tsx';
import * as $NASMenu from './islands/NASMenu.tsx';
import * as $NASMenuIcon from './islands/NASMenuIcon.tsx';
import * as $components_Arrow from './islands/components/Arrow.tsx';
import * as $components_NavigationIndicator from './islands/components/NavigationIndicator.tsx';
import * as $contexts_ContextProvider from './islands/contexts/ContextProvider.tsx';
import * as $contexts_Mask from './islands/contexts/Mask.tsx';
import * as $contexts_Router from './islands/contexts/Router.tsx';
import * as $contexts_WindowEvents from './islands/contexts/WindowEvents.tsx';
import { type Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/_404.tsx': $_404,
    './routes/_app.tsx': $_app,
    './routes/future/_layout.tsx': $future_layout,
    './routes/future/index.tsx': $future_index,
    './routes/game/_layout.tsx': $game_layout,
    './routes/game/index.tsx': $game_index,
    './routes/index.tsx': $index,
    './routes/monitor/_layout.tsx': $monitor_layout,
    './routes/monitor/index.tsx': $monitor_index,
    './routes/nas/_layout.tsx': $nas_layout,
    './routes/nas/index.tsx': $nas_index,
    './routes/nas/upload.tsx': $nas_upload,
  },
  islands: {
    './islands/AnimationProvider.tsx': $AnimationProvider,
    './islands/NASMenu.tsx': $NASMenu,
    './islands/NASMenuIcon.tsx': $NASMenuIcon,
    './islands/components/Arrow.tsx': $components_Arrow,
    './islands/components/NavigationIndicator.tsx': $components_NavigationIndicator,
    './islands/contexts/ContextProvider.tsx': $contexts_ContextProvider,
    './islands/contexts/Mask.tsx': $contexts_Mask,
    './islands/contexts/Router.tsx': $contexts_Router,
    './islands/contexts/WindowEvents.tsx': $contexts_WindowEvents,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
